version: '3.9'

services:
  redis:
    image: redis:latest
    command: redis-server
    ports:
      - "6379:6379"
  sidekiq:
    depends_on:
      - redis
    build: .
    env_file:
      - .env
  web:
    depends_on:
      - sidekiq
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - .env
